### ISSUE TITLE
Submit to functional and reusable 

### ISSUE THREAD

**Issue by ForeverZyh** [researchart/fse20#2]
I find that functional and reusable are two levels of Artifacts Evaluated. (https://www.acm.org/publications/policies/artifact-review-badging)

To get a badge for Artifacts Evaluated, is it necessary to submit to both functional and reusable? Or it will be more appropriate to submit to only one of them and let the reviewers decide which badge the submission deserves?

**Comment by kstolee** [comment]
It's possible to earn multiple badges, but it's easier for the committee if everything is in one place.

If you want to apply for N badges, then make N subdirectories. Put all the files in one, and point to the others from that one.
